; =============================================================
; Big NTP Clock — PlatformIO project config
; Target: Seeed Studio XIAO ESP32-C3
; =============================================================

[env:xiao_esp32c3]
platform  = espressif32
board     = seeed_xiao_esp32c3
framework = arduino

; ---- Serial monitor ----
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; ---- OTA upload ----
; ---- Set your IP address here accordingly
upload_protocol = espota
upload_port     = 192.168.0.122
upload_flags    =
    --auth=

; ---- USB upload (uncomment and comment OTA above when using USB) ----
; upload_protocol = esptool
; upload_port     = /dev/cu.usbmodem101
; upload_speed    = 921600

; ---- Libraries ----
lib_deps =
    adafruit/Adafruit NeoPixel
    knolleary/PubSubClient
    arduino-libraries/NTPClient
    paulstoffregen/Time

; ---- Build flags ----
build_flags =
    -DCORE_DEBUG_LEVEL=0
